repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
        args:
          - "--format=json"
  - repo: https://github.com/ipfans/pre-commit-hooks
    rev: v0.1.0
    hooks:
      - id: commig-msg-checker
        stages:
          - commit-msg
